context:
  name: cargo-binutils
  version: "0.3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/rust-embedded/cargo-binutils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 431fb12a47fafcb7047d41bdf4a4c9b77bea56856e0ef65c12c40f5fcb15f98f

build:
  number: 1

  script:
    - if: unix
      then:
        - cargo install --locked --bins --root ${PREFIX} --path . --no-track
        - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      else:
        - cargo install --locked --bins --root %PREFIX% --path . --no-track
        - cargo-bundle-licenses --format yaml --output %SRC_DIR%\THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: linux and not x86_64
      then:
        - ${{ compiler('c') }}
  run:
    - llvm-tools
    - rust

tests:
  - package_contents:
      bin:
        - cargo-cov
        - cargo-nm
        - cargo-objcopy
        - cargo-objdump
        - cargo-profdata
        - cargo-readobj
        - cargo-size
        - cargo-strip
        - rust-ar
        - rust-cov
        - rust-ld
        - rust-lld
        - rust-nm
        - rust-objcopy
        - rust-objdump
        - rust-profdata
        - rust-readobj
        - rust-size
        - rust-strip
  - script:
      - cargo-cov --version
      - cargo-nm --version
      - cargo-objcopy --version
      - cargo-objdump --version
      - cargo-profdata --version
      - cargo-readobj --version
      - cargo-size --version
      - cargo-strip --version
      - rust-ar --version
      - rust-cov --version
      - rust-nm --version
      - rust-objcopy --version
      - rust-objdump --version
      - rust-profdata --version
      - rust-readobj --version
      - rust-size --version
      - rust-strip --version

about:
  homepage: https://github.com/rust-embedded/cargo-binutils
  summary: 'Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain'
  description: |
    Cargo subcommands to invoke the LLVM tools shipped with the Rust toolchain
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  repository: https://github.com/rust-embedded/cargo-binutils

extra:
  recipe-maintainers:
    - MementoRC
